_format_version: "1.1"
services:
  - name: mail-service
    protocol: grpc
    host: mail-service
    port: 6666
    routes:
      - name: mail-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.mail.MailService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: auth-service
    protocol: grpc
    host: auth-service
    port: 7777
    routes:
      - name: auth-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.auth.AuthService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: user-service
    protocol: grpc
    host: user-service
    port: 8888
    routes:
      - name: user-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.user.UserService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: parkinglot-service
    protocol: grpc
    host: parkinglot-service
    port: 9999
    routes:
      - name: parkinglot-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.parkinglot.ParkingLotService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000