_format_version: "1.1"
services:
  - name: mail-service
    protocol: grpc
    host: grpc-saigon-parking-mail-service.service.saigonparking-dc.consul
    plugins:
      - name: rate-limiting
        config:
          second: 3
          minute: 150
          policy: local
    routes:
      - name: mail-http
        protocols:
          - http
        paths:
          - /com.bht.saigonparking.api.grpc.mail.MailService/
        plugins:
          - name: grpc-web
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Authorization
                - Cache-Control
                - Cookie
                - Content-Length
                - Content-MD5
                - Content-Transfer-Encoding
                - Content-Type
                - Custom-Header-1
                - Date
                - Grpc-Timeout
                - Keep-Alive
                - X-Accept-Content-Transfer-Encoding
                - X-Accept-Response-Streaming
                - X-Auth-Token
                - X-Grpc-Web
                - X-User-Agent
              credentials: false
              max_age: 3600
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: auth-service
    protocol: grpc
    host: grpc-saigon-parking-auth-service.service.saigonparking-dc.consul
    plugins:
      - name: rate-limiting
        config:
          second: 3
          minute: 150
          policy: local
    routes:
      - name: auth-http
        protocols:
          - http
        paths:
          - /com.bht.saigonparking.api.grpc.auth.AuthService/
        plugins:
          - name: grpc-web
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Authorization
                - Cache-Control
                - Cookie
                - Content-Length
                - Content-MD5
                - Content-Transfer-Encoding
                - Content-Type
                - Custom-Header-1
                - Date
                - Grpc-Timeout
                - Keep-Alive
                - X-Accept-Content-Transfer-Encoding
                - X-Accept-Response-Streaming
                - X-Auth-Token
                - X-Grpc-Web
                - X-User-Agent
              credentials: false
              max_age: 3600
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: user-service
    protocol: grpc
    host: grpc-saigon-parking-user-service.service.saigonparking-dc.consul
    plugins:
      - name: rate-limiting
        config:
          second: 3
          minute: 150
          policy: local
    routes:
      - name: user-http
        protocols:
          - http
        paths:
          - /com.bht.saigonparking.api.grpc.user.UserService/
        plugins:
          - name: grpc-web
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Authorization
                - Cache-Control
                - Cookie
                - Content-Length
                - Content-MD5
                - Content-Transfer-Encoding
                - Content-Type
                - Custom-Header-1
                - Date
                - Grpc-Timeout
                - Keep-Alive
                - X-Accept-Content-Transfer-Encoding
                - X-Accept-Response-Streaming
                - X-Auth-Token
                - X-Grpc-Web
                - X-User-Agent
              credentials: false
              max_age: 3600
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: parkinglot-service
    protocol: grpc
    host: grpc-saigon-parking-parkinglot-service.service.saigonparking-dc.consul
    plugins:
      - name: rate-limiting
        config:
          second: 3
          minute: 150
          policy: local
    routes:
      - name: parkinglot-http
        protocols:
          - http
        paths:
          - /com.bht.saigonparking.api.grpc.parkinglot.ParkingLotService/
        plugins:
          - name: grpc-web
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Authorization
                - Cache-Control
                - Cookie
                - Content-Length
                - Content-MD5
                - Content-Transfer-Encoding
                - Content-Type
                - Custom-Header-1
                - Date
                - Grpc-Timeout
                - Keep-Alive
                - X-Accept-Content-Transfer-Encoding
                - X-Accept-Response-Streaming
                - X-Auth-Token
                - X-Grpc-Web
                - X-User-Agent
              credentials: false
              max_age: 3600
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000