_format_version: "1.1"

services:
  - name: contact-service-websocket
    protocol: http
    host: saigon-parking-contact-service.service.saigonparking-dc.consul
    routes:
      - name: contact-http
        protocols:
          - http
        paths:
          - /contact
        plugins:
          - name: response-transformer
            config:
              add:
                headers: ["Upgrade:websocket"]
    retries: 3
    read_timeout: 86400000
    write_timeout: 86400000
    connect_timeout: 86400000


  - name: contact-service
    protocol: grpc
    host: grpc-saigon-parking-contact-service.service.saigonparking-dc.consul
    routes:
      - name: contact-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.contact.ContactService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: booking-service
    protocol: grpc
    host: grpc-saigon-parking-booking-service.service.saigonparking-dc.consul
    routes:
      - name: booking-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.booking.BookingService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: auth-service
    protocol: grpc
    host: grpc-saigon-parking-auth-service.service.saigonparking-dc.consul
    routes:
      - name: auth-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.auth.AuthService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: user-service
    protocol: grpc
    host: grpc-saigon-parking-user-service.service.saigonparking-dc.consul
    routes:
      - name: user-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.user.UserService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000


  - name: parkinglot-service
    protocol: grpc
    host: grpc-saigon-parking-parkinglot-service.service.saigonparking-dc.consul
    routes:
      - name: parkinglot-grpc
        protocols:
          - grpc
        paths:
          - /com.bht.saigonparking.api.grpc.parkinglot.ParkingLotService/
    retries: 3
    read_timeout: 30000
    write_timeout: 30000
    connect_timeout: 30000