version: '3'
networks:
  saigonparkingmap:
    driver: bridge

services:
  
  appserver:
    image: saigonparkingmap/appserver:v1.0.1
    networks:
      - saigonparkingmap
    environment:
      TZ: Asia/Bangkok
    ports:
      - "9090:9090"
      - "9999:9999"