version: '3'

networks:
  saigonparking-service:
    driver: bridge

services:
  service-discovery:
    image: ${DOCKER_HUB_ID}/discovery:${SERVICE_DISCOVERY_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${SERVICE_DISCOVERY_DNS_PORT}:${SERVICE_DISCOVERY_DNS_PORT}/udp"
      - "${SERVICE_DISCOVERY_HTTP_PORT}:${SERVICE_DISCOVERY_HTTP_PORT}"
      - "${SERVICE_DISCOVERY_GRPC_PORT}:${SERVICE_DISCOVERY_GRPC_PORT}"

  message-queue:
    image: ${DOCKER_HUB_ID}/queue:${MESSAGE_QUEUE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
      RABBITMQ_CONFIG_FILE:                 ${RABBITMQ_CONFIG_FILE}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS:  ${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    ports:
      - "${MESSAGE_QUEUE_PORT}:${MESSAGE_QUEUE_PORT}"
      - "${MESSAGE_QUEUE_MANAGEMENT_PORT}:${MESSAGE_QUEUE_MANAGEMENT_PORT}"
    links:
      - service-discovery

  mail-service:
    image: ${DOCKER_HUB_ID}/mail-service:${MAIL_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      WEB_DOMAIN:             ${SAIGON_PARKING_DOMAIN}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  auth-service:
    image: ${DOCKER_HUB_ID}/auth-service:${AUTH_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${AUTH_SERVICE_ID}
      SERVICE_HOST:           ${AUTH_SERVICE_HOST}
      SERVICE_PORT:           ${AUTH_SERVICE_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  booking-service:
    image: ${DOCKER_HUB_ID}/booking-service:${BOOKING_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${BOOKING_SERVICE_ID}
      SERVICE_HOST:           ${BOOKING_SERVICE_HOST}
      SERVICE_PORT:           ${BOOKING_SERVICE_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${BOOKING_SERVICE_PORT}:${BOOKING_SERVICE_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  user-service-1:
    image: ${DOCKER_HUB_ID}/user-service:${USER_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${USER_SERVICE_1_ID}
      SERVICE_HOST:           ${USER_SERVICE_1_HOST}
      SERVICE_PORT:           ${USER_SERVICE_1_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${USER_SERVICE_1_PORT}:${USER_SERVICE_1_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  user-service-2:
    image: ${DOCKER_HUB_ID}/user-service:${USER_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${USER_SERVICE_2_ID}
      SERVICE_HOST:           ${USER_SERVICE_2_HOST}
      SERVICE_PORT:           ${USER_SERVICE_2_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${USER_SERVICE_2_PORT}:${USER_SERVICE_2_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  parkinglot-service-1:
    image: ${DOCKER_HUB_ID}/parkinglot-service:${PARKING_LOT_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${PARKING_LOT_SERVICE_1_ID}
      SERVICE_HOST:           ${PARKING_LOT_SERVICE_1_HOST}
      SERVICE_PORT:           ${PARKING_LOT_SERVICE_1_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${PARKING_LOT_SERVICE_1_PORT}:${PARKING_LOT_SERVICE_1_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  parkinglot-service-2:
    image: ${DOCKER_HUB_ID}/parkinglot-service:${PARKING_LOT_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${PARKING_LOT_SERVICE_2_ID}
      SERVICE_HOST:           ${PARKING_LOT_SERVICE_2_HOST}
      SERVICE_PORT:           ${PARKING_LOT_SERVICE_2_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${PARKING_LOT_SERVICE_2_PORT}:${PARKING_LOT_SERVICE_2_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  contact-service-1:
    image: ${DOCKER_HUB_ID}/contact-service:${CONTACT_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${CONTACT_SERVICE_1_ID}
      SERVICE_HOST:           ${CONTACT_SERVICE_1_HOST}
      SERVICE_PORT:           ${CONTACT_SERVICE_1_PORT}
      SERVICE_HTTP_PORT:      ${CONTACT_SERVICE_1_HTTP_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${CONTACT_SERVICE_1_PORT}:${CONTACT_SERVICE_1_PORT}"
      - "${CONTACT_SERVICE_1_HTTP_PORT}:${CONTACT_SERVICE_1_HTTP_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  contact-service-2:
    image: ${DOCKER_HUB_ID}/contact-service:${CONTACT_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ:                     ${TIMEZONE}
      SERVICE_ID:             ${CONTACT_SERVICE_2_ID}
      SERVICE_HOST:           ${CONTACT_SERVICE_2_HOST}
      SERVICE_PORT:           ${CONTACT_SERVICE_2_PORT}
      SERVICE_HTTP_PORT:      ${CONTACT_SERVICE_2_HTTP_PORT}
      DATABASE_HOST:          ${DATABASE_HOST}
      DATABASE_PORT:          ${DATABASE_PORT}
      MESSAGE_QUEUE_HOST:     ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PORT:     ${MESSAGE_QUEUE_PORT}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    ports:
      - "${CONTACT_SERVICE_2_PORT}:${CONTACT_SERVICE_2_PORT}"
      - "${CONTACT_SERVICE_2_HTTP_PORT}:${CONTACT_SERVICE_2_HTTP_PORT}"
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery