version: '3'
networks:
  saigonparking-service:
    driver: bridge

services:

  user-service:
    image: ${DOCKER_HUB_ID}/user-service:${USER_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${USER_SERVICE_HTTP_PORT}:${USER_SERVICE_HTTP_PORT}"
      - "${USER_SERVICE_GRPC_PORT}:${USER_SERVICE_GRPC_PORT}"

  parkinglot-service:
    image: ${DOCKER_HUB_ID}/parkinglot-service:${PARKING_LOT_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${PARKING_LOT_SERVICE_HTTP_PORT}:${PARKING_LOT_SERVICE_HTTP_PORT}"
      - "${PARKING_LOT_SERVICE_GRPC_PORT}:${PARKING_LOT_SERVICE_GRPC_PORT}"