version: '3'
networks:
  kong-net:
    driver: bridge

services:
  webserver:
    image: saigonparkingmap/webserver:v1.0
    networks:
      - kong-net
    environment:
      TZ: Asia/Bangkok
    ports:
      - "80:8080"
      - "443:8443"
  
  
  kong-database:
    image: postgres:9.6
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      TZ:                 Asia/Bangkok
      PGTZ:               Asia/Bangkok
      POSTGRES_DB:        kong
      POSTGRES_USER:      kong
      POSTGRES_PASSWORD:  kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
  
  
  kong-migration:
    image: kong:2.0.2
    networks:
      - kong-net
    environment:
      TZ:                 Asia/Bangkok
      KONG_DATABASE:      postgres
      KONG_PG_HOST:       kong-database
      KONG_PG_DATABASE:   kong
      KONG_PG_USER:       kong
      KONG_PG_PASSWORD:   kong
    links:
      - kong-database
    depends_on:
      - kong-database
    command: "kong migrations bootstrap"
    restart: on-failure
  
  
  gateway:
    image: kong:2.0.2
    networks:
      - kong-net
    environment:
      TZ:                 Asia/Bangkok
      KONG_LOG_LEVEL:     info
      #KONG_SSL_CERT:      /
      #KONG_SSL_CERT_KEY:  /
      KONG_DATABASE:      postgres
      KONG_PG_HOST:       kong-database
      KONG_PG_DATABASE:   kong
      KONG_PG_USER:       kong
      KONG_PG_PASSWORD:   kong
      KONG_PROXY_LISTEN:  0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "9080:9080"
      - "9081:9081"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    depends_on:
      - kong-database
      - kong-migration
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 2s
      retries: 15
    restart: on-failure
  
  
  appserver:
    image: saigonparkingmap/appserver:v1.0
    networks:
      - kong-net
    environment:
      TZ: Asia/Bangkok
    ports:
      - "9090:9090"
      - "9999:9999"
    depends_on:
      - gateway