version: '3'
networks:
  saigonparking-service:
    driver: bridge

services:

  appserver:
    image: ${DOCKER_HUB_ID}/appserver:${APP_SERVER_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${APP_SERVER_HTTP_PORT}:${APP_SERVER_HTTP_PORT}"
      - "${APP_SERVER_GRPC_PORT}:${APP_SERVER_GRPC_PORT}"