version: '3'

networks:
  saigonparking-service:
    driver: bridge

services:
  message-queue:
    image: ${DOCKER_HUB_ID}/queue:${MESSAGE_QUEUE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
      RABBITMQ_CONFIG_FILE:                 ${RABBITMQ_CONFIG_FILE}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS:  ${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    ports:
      - "${MESSAGE_QUEUE_PORT}:${MESSAGE_QUEUE_PORT}"
      - "${MESSAGE_QUEUE_MANAGEMENT_PORT}:${MESSAGE_QUEUE_MANAGEMENT_PORT}"

  mail-service:
    image: ${DOCKER_HUB_ID}/mail-service:${MAIL_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${MAIL_SERVICE_HTTP_PORT}:${MAIL_SERVICE_HTTP_PORT}"
      - "${MAIL_SERVICE_GRPC_PORT}:${MAIL_SERVICE_GRPC_PORT}"
    depends_on:
      - message-queue

  auth-service:
    image: ${DOCKER_HUB_ID}/auth-service:${AUTH_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${AUTH_SERVICE_HTTP_PORT}:${AUTH_SERVICE_HTTP_PORT}"
      - "${AUTH_SERVICE_GRPC_PORT}:${AUTH_SERVICE_GRPC_PORT}"
    depends_on:
      - message-queue

  user-service:
    image: ${DOCKER_HUB_ID}/user-service:${USER_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${USER_SERVICE_HTTP_PORT}:${USER_SERVICE_HTTP_PORT}"
      - "${USER_SERVICE_GRPC_PORT}:${USER_SERVICE_GRPC_PORT}"
    depends_on:
      - message-queue

  parkinglot-service:
    image: ${DOCKER_HUB_ID}/parkinglot-service:${PARKING_LOT_SERVICE_VERSION}
    networks:
      - saigonparking-service
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${PARKING_LOT_SERVICE_HTTP_PORT}:${PARKING_LOT_SERVICE_HTTP_PORT}"
      - "${PARKING_LOT_SERVICE_GRPC_PORT}:${PARKING_LOT_SERVICE_GRPC_PORT}"
    depends_on:
      - message-queue