version: '3'

networks:
  saigonparking:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  proxy:
    image: ${DOCKER_HUB_ID}/proxy:${PROXY_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.1
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}"
      - "${PROXY_HTTP_SSL_PORT}:${PROXY_HTTP_SSL_PORT}"
      - "127.0.0.1:${PROXY_ADMIN_PORT}:${PROXY_ADMIN_PORT}"

  gateway:
    image: ${DOCKER_HUB_ID}/gateway:${GATEWAY_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.2
    environment:
      TZ:                       ${TIMEZONE}
      KONG_DNS_RESOLVER:        ${KONG_DNS_RESOLVER}
      KONG_LOG_LEVEL:           ${KONG_LOG_LEVEL}
      KONG_DATABASE:            ${KONG_DATABASE}
      KONG_SSL_CERT:            ${KONG_SSL_CERT_PATH}
      KONG_SSL_CERT_KEY:        ${KONG_SSL_CERT_KEY_PATH}
      KONG_MEM_CACHE_SIZE:      ${KONG_MEM_CACHE_SIZE}
      KONG_DECLARATIVE_CONFIG:  ${KONG_DECLARATIVE_CONFIG}
      KONG_PROXY_LISTEN:        ${KONG_PROXY_LISTEN}
      KONG_ADMIN_LISTEN:        ${KONG_ADMIN_LISTEN}
      KONG_PLUGINS:             ${KONG_PLUGINS}
    ports:
      - "${KONG_HTTP_PORT}:${KONG_HTTP_PORT}"
      - "${KONG_HTTP_SSL_PORT}:${KONG_HTTP_SSL_PORT}"
      - "${KONG_GRPC_PORT}:${KONG_GRPC_PORT}"
      - "${KONG_GRPC_SSL_PORT}:${KONG_GRPC_SSL_PORT}"
      - "127.0.0.1:${KONG_ADMIN_PORT}:${KONG_ADMIN_PORT}"
      - "127.0.0.1:${KONG_ADMIN_SSL_PORT}:${KONG_ADMIN_SSL_PORT}"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 2s
      retries: 15
    restart: on-failure

  #  gateway-grpc:
  #    image: ${DOCKER_HUB_ID}/gateway:${GATEWAY_VERSION}
  #    networks:
  #      saigonparking
  #        ipv4_address: 172.28.1.3
  #    environment:
  #      TZ:                       ${TIMEZONE}
  #      KONG_LOG_LEVEL:           ${KONG_LOG_LEVEL}
  #      KONG_DATABASE:            ${KONG_DATABASE}
  #      KONG_SSL_CERT:            ${KONG_SSL_CERT_PATH}
  #      KONG_SSL_CERT_KEY:        ${KONG_SSL_CERT_KEY_PATH}
  #      KONG_MEM_CACHE_SIZE:      ${KONG_MEM_CACHE_SIZE}
  #      KONG_DECLARATIVE_CONFIG:  ${KONG_GRPC_DECLARATIVE_CONFIG}
  #      KONG_PROXY_LISTEN:        ${KONG_GRPC_PROXY_LISTEN}
  #      KONG_ADMIN_LISTEN:        ${KONG_GRPC_ADMIN_LISTEN}
  #      KONG_PLUGINS:             ${KONG_GRPC_PLUGINS}
  #    ports:
  #      - "${KONG_GRPC_PORT}:${KONG_GRPC_PORT}"
  #      - "${KONG_GRPC_SSL_PORT}:${KONG_GRPC_SSL_PORT}"
  #      - "127.0.0.1:${KONG_GRPC_ADMIN_PORT}:${KONG_GRPC_ADMIN_PORT}"
  #      - "127.0.0.1:${KONG_GRPC_ADMIN_SSL_PORT}:${KONG_GRPC_ADMIN_SSL_PORT}"
  #    healthcheck:
  #      test: ["CMD", "kong", "health"]
  #      interval: 5s
  #      timeout: 2s
  #      retries: 15
  #    restart: on-failure
  #
  #  gateway-http:
  #    image: ${DOCKER_HUB_ID}/gateway:${GATEWAY_VERSION}
  #    networks:
  #      saigonparking
  #        ipv4_address: 172.28.1.4
  #    environment:
  #      TZ:                       ${TIMEZONE}
  #      KONG_LOG_LEVEL:           ${KONG_LOG_LEVEL}
  #      KONG_DATABASE:            ${KONG_DATABASE}
  #      KONG_SSL_CERT:            ${KONG_SSL_CERT_PATH}
  #      KONG_SSL_CERT_KEY:        ${KONG_SSL_CERT_KEY_PATH}
  #      KONG_MEM_CACHE_SIZE:      ${KONG_MEM_CACHE_SIZE}
  #      KONG_DECLARATIVE_CONFIG:  ${KONG_HTTP_DECLARATIVE_CONFIG}
  #      KONG_PROXY_LISTEN:        ${KONG_HTTP_PROXY_LISTEN}
  #      KONG_ADMIN_LISTEN:        ${KONG_HTTP_ADMIN_LISTEN}
  #      KONG_PLUGINS:             ${KONG_HTTP_PLUGINS}
  #    ports:
  #      - "${KONG_HTTP_PORT}:${KONG_HTTP_PORT}"
  #      - "${KONG_HTTP_SSL_PORT}:${KONG_HTTP_SSL_PORT}"
  #      - "127.0.0.1:${KONG_HTTP_ADMIN_PORT}:${KONG_HTTP_ADMIN_PORT}"
  #      - "127.0.0.1:${KONG_HTTP_ADMIN_SSL_PORT}:${KONG_HTTP_ADMIN_SSL_PORT}"
  #    healthcheck:
  #      test: ["CMD", "kong", "health"]
  #      interval: 5s
  #      timeout: 2s
  #      retries: 15
  #    restart: on-failure

  service-discovery:
    image: ${DOCKER_HUB_ID}/discovery:${SERVICE_DISCOVERY_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.5
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${SERVICE_DISCOVERY_DNS_PORT}:${SERVICE_DISCOVERY_DNS_PORT}/udp"
      - "${SERVICE_DISCOVERY_HTTP_PORT}:${SERVICE_DISCOVERY_HTTP_PORT}"
      - "${SERVICE_DISCOVERY_GRPC_PORT}:${SERVICE_DISCOVERY_GRPC_PORT}"
    depends_on:
      - gateway

  message-queue:
    image: ${DOCKER_HUB_ID}/queue:${MESSAGE_QUEUE_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.6
    environment:
      TZ:                                   ${TIMEZONE}
      RABBITMQ_CONFIG_FILE:                 ${RABBITMQ_CONFIG_FILE}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS:  ${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    ports:
      - "${MESSAGE_QUEUE_PORT}:${MESSAGE_QUEUE_PORT}"
      - "${MESSAGE_QUEUE_MANAGEMENT_PORT}:${MESSAGE_QUEUE_MANAGEMENT_PORT}"
    depends_on:
      - gateway
      - service-discovery

  mail-service:
    image: ${DOCKER_HUB_ID}/mail-service:${MAIL_SERVICE_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.7
    environment:
      TZ:           ${TIMEZONE}
      SERVICE_ID:   ${MAIL_SERVICE_ID}
      SERVICE_HOST: ${MAIL_SERVICE_HOST}
      SERVICE_PORT: ${MAIL_SERVICE_PORT}
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  auth-service:
    image: ${DOCKER_HUB_ID}/auth-service:${AUTH_SERVICE_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.8
    environment:
      TZ:           ${TIMEZONE}
      SERVICE_ID:   ${AUTH_SERVICE_ID}
      SERVICE_HOST: ${AUTH_SERVICE_HOST}
      SERVICE_PORT: ${AUTH_SERVICE_PORT}
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  user-service:
    image: ${DOCKER_HUB_ID}/user-service:${USER_SERVICE_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.9
    environment:
      TZ:           ${TIMEZONE}
      SERVICE_ID:   ${USER_SERVICE_ID}
      SERVICE_HOST: ${USER_SERVICE_HOST}
      SERVICE_PORT: ${USER_SERVICE_PORT}
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery

  parkinglot-service:
    image: ${DOCKER_HUB_ID}/parkinglot-service:${PARKING_LOT_SERVICE_VERSION}
    networks:
      saigonparking:
        ipv4_address: 172.28.1.10
    environment:
      TZ:           ${TIMEZONE}
      SERVICE_ID:   ${PARKING_LOT_SERVICE_ID}
      SERVICE_HOST: ${PARKING_LOT_SERVICE_HOST}
      SERVICE_PORT: ${PARKING_LOT_SERVICE_PORT}
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      - message-queue
      - service-discovery
    links:
      - message-queue
      - service-discovery