version: '3'

networks:
  saigonparking:
    driver: bridge

services:
  webserver:
    image: ${DOCKER_HUB_ID}/webserver:${WEB_SERVER_VERSION}
    networks:
      - saigonparking
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "80:${WEB_SERVER_HTTP_DOCKER_PORT}"
      - "443:${WEB_SERVER_HTTP_SSL_DOCKER_PORT}"

  proxy:
    image: ${DOCKER_HUB_ID}/proxy:${PROXY_VERSION}
    networks:
      - saigonparking
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}"
      - "${PROXY_HTTP_SSL_PORT}:${PROXY_HTTP_SSL_PORT}"
      - "127.0.0.1:${PROXY_ADMIN_PORT}:${PROXY_ADMIN_PORT}"

  gateway-database:
    image: postgres:${POSTGRES_VERSION}
    networks:
      - saigonparking
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    environment:
      TZ:                 ${TIMEZONE}
      PGTZ:               ${TIMEZONE}
      POSTGRES_DB:        ${KONG_PG_DATABASE}
      POSTGRES_USER:      ${KONG_PG_USER}
      POSTGRES_PASSWORD:  ${KONG_PG_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure

  gateway-migration:
    image: kong:${KONG_VERSION}
    networks:
      - saigonparking
    environment:
      TZ:                 ${TIMEZONE}
      KONG_DATABASE:      ${KONG_DATABASE}
      KONG_PG_HOST:       gateway-database
      KONG_PG_DATABASE:   ${KONG_PG_DATABASE}
      KONG_PG_USER:       ${KONG_PG_USER}
      KONG_PG_PASSWORD:   ${KONG_PG_PASSWORD}
    links:
      - gateway-database
    depends_on:
      - gateway-database
    command: "kong migrations bootstrap"
    restart: on-failure

  gateway:
    image: ${DOCKER_HUB_ID}/gateway:${GATEWAY_VERSION}
    networks:
      - saigonparking
    environment:
      TZ:                 ${TIMEZONE}
      KONG_PLUGINS:       ${KONG_PLUGINS}
      KONG_LOG_LEVEL:     ${KONG_LOG_LEVEL}
      KONG_DATABASE:      ${KONG_DATABASE}
      KONG_PG_HOST:       gateway-database
      KONG_PG_DATABASE:   ${KONG_PG_DATABASE}
      KONG_PG_USER:       ${KONG_PG_USER}
      KONG_PG_PASSWORD:   ${KONG_PG_PASSWORD}
      KONG_SSL_CERT:      ${KONG_SSL_CERT_PATH}
      KONG_SSL_CERT_KEY:  ${KONG_SSL_CERT_KEY_PATH}
      KONG_PROXY_LISTEN:  ${KONG_PROXY_LISTEN}
      KONG_ADMIN_LISTEN:  ${KONG_ADMIN_LISTEN}
    ports:
      - "${KONG_HTTP_PORT}:${KONG_HTTP_PORT}"
      - "${KONG_HTTP_SSL_PORT}:${KONG_HTTP_SSL_PORT}"
      - "${KONG_GRPC_PORT}:${KONG_GRPC_PORT}"
      - "${KONG_GRPC_SSL_PORT}:${KONG_GRPC_SSL_PORT}"
      - "127.0.0.1:${KONG_ADMIN_PORT}:${KONG_ADMIN_PORT}"
      - "127.0.0.1:${KONG_ADMIN_SSL_PORT}:${KONG_ADMIN_SSL_PORT}"
    links:
      - gateway-database
    depends_on:
      - gateway-database
      - gateway-migration
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 2s
      retries: 15
    restart: on-failure

  message-queue:
    image: ${DOCKER_HUB_ID}/queue:${MESSAGE_QUEUE_VERSION}
    networks:
      - saigonparking
    environment:
      TZ: ${TIMEZONE}
      RABBITMQ_CONFIG_FILE:                 ${RABBITMQ_CONFIG_FILE}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS:  ${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    ports:
      - "${MESSAGE_QUEUE_PORT}:${MESSAGE_QUEUE_PORT}"
      - "${MESSAGE_QUEUE_MANAGEMENT_PORT}:${MESSAGE_QUEUE_MANAGEMENT_PORT}"

  mail-service:
    image: ${DOCKER_HUB_ID}/mail-service:${MAIL_SERVICE_VERSION}
    networks:
      - saigonparking
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${MAIL_SERVICE_HTTP_PORT}:${MAIL_SERVICE_HTTP_PORT}"
      - "${MAIL_SERVICE_GRPC_PORT}:${MAIL_SERVICE_GRPC_PORT}"

  auth-service:
    image: ${DOCKER_HUB_ID}/auth-service:${AUTH_SERVICE_VERSION}
    networks:
      - saigonparking
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${AUTH_SERVICE_HTTP_PORT}:${AUTH_SERVICE_HTTP_PORT}"
      - "${AUTH_SERVICE_GRPC_PORT}:${AUTH_SERVICE_GRPC_PORT}"

  user-service:
    image: ${DOCKER_HUB_ID}/user-service:${USER_SERVICE_VERSION}
    networks:
      - saigonparking
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${USER_SERVICE_HTTP_PORT}:${USER_SERVICE_HTTP_PORT}"
      - "${USER_SERVICE_GRPC_PORT}:${USER_SERVICE_GRPC_PORT}"

  parkinglot-service:
    image: ${DOCKER_HUB_ID}/parkinglot-service:${PARKING_LOT_SERVICE_VERSION}
    networks:
      - saigonparking
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${PARKING_LOT_SERVICE_HTTP_PORT}:${PARKING_LOT_SERVICE_HTTP_PORT}"
      - "${PARKING_LOT_SERVICE_GRPC_PORT}:${PARKING_LOT_SERVICE_GRPC_PORT}"